/* eslint-disable  */

// flow-typed signature: 58766695ed13cf456cabaff6a6fdb1eb
// flow-typed version: <<STUB>>/@chronobank_vhttps://github.com/ChronoBank/ChronoMint.git#89c4e00ff3cdef0d06af2296493446d9ec8cbc85/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chronobank'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import {
  List as iList,
  Map as iMap,
  Record as iRecord,
} from 'immutable'
import { BigNumber } from 'bignumber.js'

import AbstractFetchingCollection from 'models/AbstractFetchingCollection'
import AbstractFetchingModel from 'models/AbstractFetchingModel'
import AbstractModel from 'models/AbstractModel'
import AddressesCollection from 'models/wallet/AddressesCollection'
import AllowanceCollection from 'models/wallet/AllowanceCollection'
import AllowanceModel from 'models/wallet/AllowanceModel'
import Amount from 'models/Amount'
import BalanceModel from 'models/tokens/BalanceModel'
import BalancesCollection from 'models/tokens/BalancesCollection'
import BlacklistModel from 'models/tokens/BlacklistModel'
import FeeModel from 'models/tokens/FeeModel'
import MultisigWalletPendingTxCollection from 'models/wallet/MultisigWalletPendingTxCollection'
import OwnerCollection from 'models/wallet/OwnerCollection'
import OwnerModel from 'models/wallet/OwnerModel'
import TokenModel from 'models/tokens/TokenModel'
import TransactionsCollection from 'models/wallet/TransactionsCollection'
import TxModel from 'models/TxModel'

// declare module '@chronobank' {
//   declare export default any;
// }

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// declare module '@chronobank/i18nJson' {
//   declare export default any;
// }

// declare module '@chronobank/main' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login-ui/lang' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login-ui/settings' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/__mocks__/sockjs-client' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/AbstractNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/AbstractProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinAbstractNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinBlockexplorerNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinEngine' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinMiddlewareNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/BitcoinUtils' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/EthereumEngine' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/EthereumMiddlewareNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/EthereumNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/EthereumProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/ExchangeProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/HardwareWallet' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/LedgerProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/metaMaskResolver' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/mnemonicProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/mnemonicProvider.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/MonitorService' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemAbstractNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemEngine' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemMiddlewareNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemNode' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemUtils' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NemWallet' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NetworkProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/NetworkService' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/privateKeyProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/privateKeyProvider.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/PublicBackendProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/settings' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/TrezorProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/uportProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/walletGenerator' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/walletGenerator.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/walletProvider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/Web3Provider' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/network/Web3Utils' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ducks' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ledger/actions' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ledger/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ledger/index' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ledger/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/ledger/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/monitor/actions' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/monitor/index' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/monitor/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/network/actions' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/network/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/network/index' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/network/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/network/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/trezor/actions' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/trezor/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/trezor/index' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/trezor/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/redux/trezor/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/packages/login/settings' {
//   declare export default any;
// }

// declare module '@chronobank/scripts/build' {
//   declare export default any;
// }

// declare module '@chronobank/scripts/compress' {
//   declare export default any;
// }

// declare module '@chronobank/scripts/i18npack' {
//   declare export default any;
// }

// declare module '@chronobank/scripts/importSort' {
//   declare export default any;
// }

// declare module '@chronobank/scripts/start' {
//   declare export default any;
// }

// declare module '@chronobank/src/app' {
//   declare export default any;
// }

// declare module '@chronobank/src/assets/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/abi/ERC20DAODefaultABI' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/abi/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AbstractContractDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AbstractMultisigContractDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AbstractTokenDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AssetDonatorDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AssetHolderDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/AssetsManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/BitcoinDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ChronoBankAssetDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ChronoBankAssetProxyDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ChronoBankPlatformDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ContractsManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ERC20DAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ERC20ManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/EthereumDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ExchangeDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/ExchangeManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/FakeCoinDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/FeeInterfaceDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/LHTDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/LOCManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/MultisigWalletDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/MultisigWalletsManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/NemDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/PendingManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/PlatformsManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/PlatformTokenExtensionGatewayManagerEmitterDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/PollEmitterDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/PollInterfaceDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/RewardsDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/TokenManagementExtensionDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/UserManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/dao/VotingManagerDAO' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/en-notices' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/en-tx-bitcoin' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/en-tx-general' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/en-tx-nem' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/en' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18n/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/i18nApp' {
//   declare export default any;
// }

// declare module '@chronobank/src/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/Login/network/VotingProvider' {
//   declare export default any;
// }

// declare module '@chronobank/src/market/__mocks__/socket.io-client' {
//   declare export default any;
// }

// declare module '@chronobank/src/market/ccc-streamer-utilities' {
//   declare export default any;
// }

// declare module '@chronobank/src/market/MarketSocket' {
//   declare export default any;
// }

// declare module '@chronobank/src/menu' {
//   declare export default any;
// }

declare module 'models/AbstractFetchingCollection' {
  declare export default class AbstractFetchingCollection extends AbstractFetchingModel {
    add (item?: any): iMap;
    emptyModel (value: any): ?iMap;
    filter (predicate: (...args: any[]) => any): iMap;
    first (forceEmptyModel: boolean): ?any;
    hasSelected (): boolean;
    item (id: string): ?any;
    itemFetched (item: any): number;
    items (): any[];
    leftToFetch (value?: number): number;
    list (value?: any): iMap;
    merge (item?: any): iMap;
    remove (itemOrId: string | any): iMap;
    selected (id: any): iMap;
    size (): number;
    sortBy (predicate: (...args: any[]) => any): iMap;
    update (item?: any): iMap;
  }
}

// declare module '@chronobank/src/models/AdditionalActionModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/assetHolder/AssetHolderModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/assetHolder/AssetModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/assetHolder/AssetsCollection' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/assetsManager/MainAssetsManagerModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/CBEModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/constants' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/exchange/ExchangeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/exchange/ExchangeOrderModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/exchange/ExchangesCollection' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/FileSelect/FileCollection' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/FileSelect/FileExtension' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/FileSelect/FileModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/LOCModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/LOCModel.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/AbstractNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/ApprovalNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/ArbitraryNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/AssetsManagerNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/CBENoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/CBENoticeModel.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/ErrorNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/LOCNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/OperationNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/PollNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/ProfileNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/TokenNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/TransactionErrorNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/TransferErrorNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/TransferNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/notices/WalletNoticeModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/OperationModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/PollDetailsModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/PollModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/ProfileModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/ProfileModel.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/AbstractPeriodModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsCollection' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsCurrentPeriodModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsModel.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsPeriodModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/rewards/RewardsPeriodModel.spec' {
//   declare export default any;
// }

declare module 'models/wallet/MainWalletModel' {
  declare export default class MainWalletModel extends AbstractFetchingModel {
    address (): ?string;
    addresses (value: AddressesCollection): AddressesCollection;
    allowances (value: AllowanceCollection): AllowanceCollection;
    balance (balance: BalanceModel): BalancesCollection;
    balances (value: BalancesCollection): BalancesCollection;
    isMultisig (): boolean;
    isTimeLocked (): boolean;
    isTIMERequired (value: boolean): boolean | void;
    transactions (value: TxModel): TransactionsCollection;
    /**
    * @deprecated
    */
    tokens (value: iMap): iMap;
  }
}

declare module 'models/tokens/BalanceModel' {
  declare export default class BalanceModel extends AbstractFetchingModel {
    id (): ?string;
    amount (value?: Amount): ?Amount;
    symbol (): ?string;
    updateBalance (isCredited: boolean, value: BigNumber): ?Amount | void;
  }
}

declare module 'models/tokens/BalancesCollection' {
  declare export default class BalancesCollection extends AbstractFetchingCollection {
    // Yep. Empty.
  }
}

declare module 'models/AbstractModel' {
  declare export default class AbstractModel extends iRecord {
    _getSet (key: string, value?: any): any;
    id (): ?string;
    summary (): any;
    txSummary (): any;
  }
}

declare module 'models/AbstractFetchingModel' {
  declare export default class AbstractFetchingModel extends AbstractModel {
    isFailed (value: boolean): boolean;
    isFetched (value: boolean): boolean;
    isFetching (value: boolean): boolean;
    isInited (value: boolean): boolean;
    isPending (value: boolean): boolean;
    isSelected (value: boolean): boolean;
    transactionHash (value?: string): ?string;
  }
}

declare module 'models/tokens/BlacklistModel' {
  declare export default class BlacklistModel extends AbstractFetchingModel {
    add (value: any): iList;
    delete (value: any): iList;
    list (value: any): ?iList;
  }
}

declare module 'models/tokens/FeeModel' {
  declare export default class FeeModel extends AbstractFetchingModel {
    fee (value?: any): ?BigNumber;
    feeAddress (value?: string): ?string;
    withFee (value?: any): ?BigNumber;
  }
}

// declare module '@chronobank/src/models/tokens/PausedModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/tokens/ReissuableModel' {
//   declare export default any;
// }

declare module 'models/Amount' {
  declare export default class Amount {
    constructor (value: number | string | BigNumber, symbol: string, isLoaded?: boolean): Amount;

    div (value: number | string | BigNumber, base?: number): Amount;
    isLoaded (value: boolean): boolean | void;
    minus (value: number | string | BigNumber, base?: number): Amount;
    mul (value: number | string | BigNumber, base?: number): Amount;
    plus (value: number | string | BigNumber, base?: number): Amount;
    symbol (value: any): string;
  }
}

declare module 'models/tokens/TokenModel' {
  declare export default class TokenModel extends AbstractFetchingModel {
    addDecimals (amount: BigNumber): BigNumber;
    address (): ?string;
    blacklist (value: BlacklistModel): any;
    blockchain (): ?string;
    dao (): ?string;
    decimals (amount: BigNumber): any;
    fee (value?: FeeModel): ?FeeModel;
    feeAddress (): any;
    feeRate (value: any): any;
    icon (): any;
    id (): ?string;
    isERC20 (value: any): any;
    isLocked (): any;
    isOptional (): any;
    isPaused (value: any): any;
    isReissuable (value: any): any;
    managersList (): any;
    name (): any;
    platform (): any;
    removeDecimals (amount: Amount | BigNumber): Amount;
    setSymbol (): any;
    symbol (): any;
    totalSupply (value: any): any;
    txSummary (): any;
    url (value: any): ?string;
    withFee (): any;

    /**
     * @deprecated
     */
    balance (): Amount;
    setBalance (newBalance: Amount): TokenModel;
    updateBalance (isCredited: any, amount: Amount): TokenModel;
  }
}

declare module 'models/tokens/TokensCollection' {
  /**
   * List of TokenModels
   * 
   * @export
   * @class TokensCollection
   * @extends {AbstractFetchingModel}
   */
  declare export default class TokensCollection extends AbstractFetchingCollection {
    /**
     * Get a token as TokenModel by address
     * 
     * @param {string} address 
     * @returns {TokenModel} 
     * @memberof TokensCollection
     */
    getByAddress (address: string): TokenModel;
    /**
     * Get a token as TokenModel by symbol
     * 
     * @param {string} symbol 
     * @returns {TokenModel} 
     * @memberof TokensCollection
     */
    getBySymbol (symbol: string): TokenModel;
  }
}

// declare module '@chronobank/src/models/TransferError' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/TransferExecModel' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/TxError' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/TxExecModel' {
//   declare export default any;
// }

declare module 'models/TxModel' {
  declare export default class TxModel extends AbstractModel {
    args (): ?any;
    by (): ?string;
    date (format: string): string;
    fee (): BigNumber;
    from (): ?string;
    id (): ?string;
    isCredited (): ?boolean;
    isFromEmpty (): boolean;
    sign (): '+' | '-';
    symbol (): string;
    time (): ?string;
    to (): ?string;
    tokenAddress (value: any): ?string;
    type (): ?any;
    value (): BigNumber;
    /**
    * @deprecated
    */
    token (value: any): ?any;
  }
}

// declare module '@chronobank/src/models/validator' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/validator.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/voting/VotingCollection' {
//   declare export default any;
// }

// declare module '@chronobank/src/models/voting/VotingMainModel' {
//   declare export default any;
// }

declare module 'models/wallet/AddressesCollection' {
  declare export default class AddressesCollection extends AbstractFetchingCollection {
    // Yep. Empty.
  }
}

// declare module '@chronobank/src/models/wallet/AddressModel' {
//   declare export default any;
// }

declare module '@chronobank/src/models/wallet/AllowanceCollection' {
  declare export default class AddressesCollection extends AbstractFetchingCollection {
    item (spender: string, tokenId: string): ?AllowanceModel;
  }
}

declare module '@chronobank/src/models/wallet/AllowanceModel' {
  declare export default class AllowanceModel extends AbstractFetchingModel {
    id (): string;
    amount (value?: Amount): ?Amount;
  }
}

// declare module '@chronobank/src/models/wallet/MultisigTransactionModel' {
//   declare export default any;
// }

declare module 'models/wallet/MultisigWalletCollection' {
  declare export default class MultisigWalletCollection extends AbstractFetchingCollection {}
}

declare module 'models/wallet/MultisigWalletModel' {
  declare export default class MultisigWalletModel extends AbstractFetchingModel {
    address (): ?string;
    addresses (value: AddressesCollection): AddressesCollection;
    balance (balance: BalanceModel): BalancesCollection;
    isMultisig (): boolean;
    isNew (): boolean;
    isTimeLocked (): boolean;
    owners (): ?OwnerCollection; 
    ownersArray (): OwnerModel[];
    pendingCount (): number;
    pendingTxList (value: any): MultisigWalletPendingTxCollection; // TODO
    releaseTime (): Date;
    requiredSignatures (): number;
    transactions (value: TxModel): TransactionsCollection;
    txSummary (): {
      owners: OwnerModel[],
      requiredSignatures: number,
    };
    toAddFormJS (): {
      requiredSignatures: number,
      owners: OwnerModel[],
      timeLockDate: Date,
      timeLockTime: Date,
    };
    toCreateWalletTx (): {
      requiredSignatures: number,
      owners: OwnerModel[],
    };
    toRequiredSignaturesFormJS (): {
      ownersCount: number,
      requiredSignatures: number,
    };
    /**
    * @deprecated
    */
    tokens (value: iMap): iMap;
  }
}

// declare module '@chronobank/src/models/wallet/MultisigWalletModel.spec' {
//   declare export default any;
// }

declare module '@chronobank/src/models/wallet/MultisigWalletPendingTxCollection' {
  declare export default class MultisigWalletPendingTxCollection extends AbstractFetchingCollection {}
}

// declare module '@chronobank/src/models/wallet/MultisigWalletPendingTxModel' {
//   declare export default any;
// }

declare module 'models/wallet/OwnerCollection' {
  declare export default class OwnerCollection extends AbstractFetchingCollection {
    add (item?: OwnerModel): iMap;
    emptyModel (value: OwnerModel): ?iMap;
    filter (predicate: (...args: any[]) => any): iMap;
    first (forceEmptyModel: boolean): ?any;
    hasSelected (): boolean;
    item (id: string): ?any;
    itemFetched (item: OwnerModel): number;
    items (): OwnerModel[];
    leftToFetch (value?: number): number;
    list (value?: any): iMap;
    merge (item?: OwnerModel): iMap;
    remove (itemOrId: OwnerModel | string): iMap;
    selected (id: string): iMap;
    size (): number;
    sortBy (predicate: (...args: any[]) => any): iMap;
    update (item?: OwnerModel): iMap;
  }
}

declare module 'models/wallet/OwnerModel' {
  declare export default class OwnerModel extends AbstractFetchingModel {
    id (): ?string;
    address (value: string): ?string;
  }
}

declare module 'models/wallet/TransactionsCollection' {
  declare export default any;
}

// declare module '@chronobank/src/platform/ErrorList' {
//   declare export default any;
// }

// declare module '@chronobank/src/platform/i18n/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/platform/icons/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/platform/imageValidator' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsHolder/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsHolder/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsHolder/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/assetsManager/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/bootstrap/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/configureStore' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/drawer/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/drawer/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/drawer/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/ducks' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/exchange/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/exchange/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/exchange/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/exchange/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/exchange/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/i18n/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/i18n/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/i18n/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/locs/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/mainWallet/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/mainWallet/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/mainWallet/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/mainWallet/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/mainWallet/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/market/action' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/market/action.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/market/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/market/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/market/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/modals/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/modals/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/modals/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/modals/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/modals/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/multisigWallet/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/multisigWallet/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/multisigWallet/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/multisigWallet/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/multisigWallet/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/notifier/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/notifier/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/notifier/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/notifier/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/notifier/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/operations/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/operations/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/operations/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/operations/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/operations/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/rewards/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/rewards/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/rewards/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/rewards/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/routing' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/saveAccountMiddleWare' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/session/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/erc20/tokens/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/erc20/tokens/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/erc20/tokens/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/erc20/tokens/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/erc20/tokens/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/user/cbe/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/user/cbe/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/user/cbe/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/settings/user/cbe/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/sides/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/sides/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/sides/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/sides/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/sides/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/tokens/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/tokens/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/tokens/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/tokens/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/ui/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/ui/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/ui/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/getters' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/voting/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/wallet/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/wallet/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/wallet/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/wallet/selectors' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/watcher/actions' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/watcher/actions.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/watcher/index' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/watcher/reducer' {
//   declare export default any;
// }

// declare module '@chronobank/src/redux/watcher/reducer.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/router' {
//   declare export default any;
// }

// declare module '@chronobank/src/services/ExchangeService' {
//   declare export default any;
// }

// declare module '@chronobank/src/services/MultisigWalletService' {
//   declare export default any;
// }

// declare module '@chronobank/src/services/TokenService' {
//   declare export default any;
// }

// declare module '@chronobank/src/services/VotingService' {
//   declare export default any;
// }

// declare module '@chronobank/src/specsInit' {
//   declare export default any;
// }

// declare module '@chronobank/src/styles' {
//   declare export default any;
// }

// declare module '@chronobank/src/styles/themes/default' {
//   declare export default any;
// }

// declare module '@chronobank/src/styles/themes/inversed' {
//   declare export default any;
// }

// declare module '@chronobank/src/styles/themes/variables' {
//   declare export default any;
// }

// declare module '@chronobank/src/themeDefault' {
//   declare export default any;
// }

// declare module '@chronobank/src/user/monitorService' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/clipboard' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/CustomSerializer' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/formatFileSize' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/formatFileSize.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/formatter' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/formatter.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/IPFS' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/IPFS.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/LocalStorage' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/LocalStorage.spec' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/SessionStorage' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/Web3Converter' {
//   declare export default any;
// }

// declare module '@chronobank/src/utils/Web3Converter.spec' {
//   declare export default any;
// }

// // Filename aliases
// declare module '@chronobank/i18nJson.js' {
//   declare export default $Exports<'@chronobank/i18nJson'>;
// }
// declare module '@chronobank/main.js' {
//   declare export default $Exports<'@chronobank/main'>;
// }
// declare module '@chronobank/packages/login-ui/lang.js' {
//   declare export default $Exports<'@chronobank/packages/login-ui/lang'>;
// }
// declare module '@chronobank/packages/login-ui/settings.js' {
//   declare export default $Exports<'@chronobank/packages/login-ui/settings'>;
// }
// declare module '@chronobank/packages/login/network/__mocks__/sockjs-client.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/__mocks__/sockjs-client'>;
// }
// declare module '@chronobank/packages/login/network/AbstractNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/AbstractNode'>;
// }
// declare module '@chronobank/packages/login/network/AbstractProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/AbstractProvider'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinAbstractNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinAbstractNode'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinBlockexplorerNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinBlockexplorerNode'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinEngine.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinEngine'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinMiddlewareNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinMiddlewareNode'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinNode'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinProvider'>;
// }
// declare module '@chronobank/packages/login/network/BitcoinUtils.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/BitcoinUtils'>;
// }
// declare module '@chronobank/packages/login/network/EthereumEngine.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/EthereumEngine'>;
// }
// declare module '@chronobank/packages/login/network/EthereumMiddlewareNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/EthereumMiddlewareNode'>;
// }
// declare module '@chronobank/packages/login/network/EthereumNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/EthereumNode'>;
// }
// declare module '@chronobank/packages/login/network/EthereumProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/EthereumProvider'>;
// }
// declare module '@chronobank/packages/login/network/ExchangeProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/ExchangeProvider'>;
// }
// declare module '@chronobank/packages/login/network/HardwareWallet.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/HardwareWallet'>;
// }
// declare module '@chronobank/packages/login/network/LedgerProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/LedgerProvider'>;
// }
// declare module '@chronobank/packages/login/network/metaMaskResolver.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/metaMaskResolver'>;
// }
// declare module '@chronobank/packages/login/network/mnemonicProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/mnemonicProvider'>;
// }
// declare module '@chronobank/packages/login/network/MonitorService.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/MonitorService'>;
// }
// declare module '@chronobank/packages/login/network/NemAbstractNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemAbstractNode'>;
// }
// declare module '@chronobank/packages/login/network/NemEngine.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemEngine'>;
// }
// declare module '@chronobank/packages/login/network/NemMiddlewareNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemMiddlewareNode'>;
// }
// declare module '@chronobank/packages/login/network/NemNode.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemNode'>;
// }
// declare module '@chronobank/packages/login/network/NemProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemProvider'>;
// }
// declare module '@chronobank/packages/login/network/NemUtils.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemUtils'>;
// }
// declare module '@chronobank/packages/login/network/NemWallet.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NemWallet'>;
// }
// declare module '@chronobank/packages/login/network/NetworkProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NetworkProvider'>;
// }
// declare module '@chronobank/packages/login/network/NetworkService.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/NetworkService'>;
// }
// declare module '@chronobank/packages/login/network/privateKeyProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/privateKeyProvider'>;
// }
// declare module '@chronobank/packages/login/network/PublicBackendProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/PublicBackendProvider'>;
// }
// declare module '@chronobank/packages/login/network/settings.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/settings'>;
// }
// declare module '@chronobank/packages/login/network/TrezorProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/TrezorProvider'>;
// }
// declare module '@chronobank/packages/login/network/uportProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/uportProvider'>;
// }
// declare module '@chronobank/packages/login/network/walletGenerator.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/walletGenerator'>;
// }
// declare module '@chronobank/packages/login/network/walletProvider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/walletProvider'>;
// }
// declare module '@chronobank/packages/login/network/Web3Provider.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/Web3Provider'>;
// }
// declare module '@chronobank/packages/login/network/Web3Utils.js' {
//   declare export default $Exports<'@chronobank/packages/login/network/Web3Utils'>;
// }
// declare module '@chronobank/packages/login/redux/ducks.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/ducks'>;
// }
// declare module '@chronobank/packages/login/redux/ledger/actions.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/ledger/actions'>;
// }
// declare module '@chronobank/packages/login/redux/ledger/index.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/ledger/index'>;
// }
// declare module '@chronobank/packages/login/redux/ledger/reducer.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/ledger/reducer'>;
// }
// declare module '@chronobank/packages/login/redux/monitor/actions.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/monitor/actions'>;
// }
// declare module '@chronobank/packages/login/redux/monitor/index.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/monitor/index'>;
// }
// declare module '@chronobank/packages/login/redux/monitor/reducer.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/monitor/reducer'>;
// }
// declare module '@chronobank/packages/login/redux/network/actions.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/network/actions'>;
// }
// declare module '@chronobank/packages/login/redux/network/index.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/network/index'>;
// }
// declare module '@chronobank/packages/login/redux/network/reducer.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/network/reducer'>;
// }
// declare module '@chronobank/packages/login/redux/trezor/actions.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/trezor/actions'>;
// }
// declare module '@chronobank/packages/login/redux/trezor/index.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/trezor/index'>;
// }
// declare module '@chronobank/packages/login/redux/trezor/reducer.js' {
//   declare export default $Exports<'@chronobank/packages/login/redux/trezor/reducer'>;
// }
// declare module '@chronobank/packages/login/settings.js' {
//   declare export default $Exports<'@chronobank/packages/login/settings'>;
// }
// declare module '@chronobank/scripts/build.js' {
//   declare export default $Exports<'@chronobank/scripts/build'>;
// }
// declare module '@chronobank/scripts/compress.js' {
//   declare export default $Exports<'@chronobank/scripts/compress'>;
// }
// declare module '@chronobank/scripts/i18npack.js' {
//   declare export default $Exports<'@chronobank/scripts/i18npack'>;
// }
// declare module '@chronobank/scripts/importSort.js' {
//   declare export default $Exports<'@chronobank/scripts/importSort'>;
// }
// declare module '@chronobank/scripts/start.js' {
//   declare export default $Exports<'@chronobank/scripts/start'>;
// }
// declare module '@chronobank/src/app.js' {
//   declare export default $Exports<'@chronobank/src/app'>;
// }
// declare module '@chronobank/src/assets/index.js' {
//   declare export default $Exports<'@chronobank/src/assets/index'>;
// }
// declare module '@chronobank/src/dao/abi/ERC20DAODefaultABI.js' {
//   declare export default $Exports<'@chronobank/src/dao/abi/ERC20DAODefaultABI'>;
// }
// declare module '@chronobank/src/dao/abi/index.js' {
//   declare export default $Exports<'@chronobank/src/dao/abi/index'>;
// }
// declare module '@chronobank/src/dao/AbstractContractDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AbstractContractDAO'>;
// }
// declare module '@chronobank/src/dao/AbstractMultisigContractDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AbstractMultisigContractDAO'>;
// }
// declare module '@chronobank/src/dao/AbstractTokenDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AbstractTokenDAO'>;
// }
// declare module '@chronobank/src/dao/AssetDonatorDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AssetDonatorDAO'>;
// }
// declare module '@chronobank/src/dao/AssetHolderDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AssetHolderDAO'>;
// }
// declare module '@chronobank/src/dao/AssetsManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/AssetsManagerDAO'>;
// }
// declare module '@chronobank/src/dao/BitcoinDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/BitcoinDAO'>;
// }
// declare module '@chronobank/src/dao/ChronoBankAssetDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ChronoBankAssetDAO'>;
// }
// declare module '@chronobank/src/dao/ChronoBankAssetProxyDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ChronoBankAssetProxyDAO'>;
// }
// declare module '@chronobank/src/dao/ChronoBankPlatformDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ChronoBankPlatformDAO'>;
// }
// declare module '@chronobank/src/dao/ContractsManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ContractsManagerDAO'>;
// }
// declare module '@chronobank/src/dao/ERC20DAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ERC20DAO'>;
// }
// declare module '@chronobank/src/dao/ERC20ManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ERC20ManagerDAO'>;
// }
// declare module '@chronobank/src/dao/EthereumDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/EthereumDAO'>;
// }
// declare module '@chronobank/src/dao/ExchangeDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ExchangeDAO'>;
// }
// declare module '@chronobank/src/dao/ExchangeManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/ExchangeManagerDAO'>;
// }
// declare module '@chronobank/src/dao/FakeCoinDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/FakeCoinDAO'>;
// }
// declare module '@chronobank/src/dao/FeeInterfaceDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/FeeInterfaceDAO'>;
// }
// declare module '@chronobank/src/dao/LHTDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/LHTDAO'>;
// }
// declare module '@chronobank/src/dao/LOCManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/LOCManagerDAO'>;
// }
// declare module '@chronobank/src/dao/MultisigWalletDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/MultisigWalletDAO'>;
// }
// declare module '@chronobank/src/dao/MultisigWalletsManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/MultisigWalletsManagerDAO'>;
// }
// declare module '@chronobank/src/dao/NemDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/NemDAO'>;
// }
// declare module '@chronobank/src/dao/PendingManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/PendingManagerDAO'>;
// }
// declare module '@chronobank/src/dao/PlatformsManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/PlatformsManagerDAO'>;
// }
// declare module '@chronobank/src/dao/PlatformTokenExtensionGatewayManagerEmitterDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/PlatformTokenExtensionGatewayManagerEmitterDAO'>;
// }
// declare module '@chronobank/src/dao/PollEmitterDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/PollEmitterDAO'>;
// }
// declare module '@chronobank/src/dao/PollInterfaceDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/PollInterfaceDAO'>;
// }
// declare module '@chronobank/src/dao/RewardsDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/RewardsDAO'>;
// }
// declare module '@chronobank/src/dao/TokenManagementExtensionDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/TokenManagementExtensionDAO'>;
// }
// declare module '@chronobank/src/dao/UserManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/UserManagerDAO'>;
// }
// declare module '@chronobank/src/dao/VotingManagerDAO.js' {
//   declare export default $Exports<'@chronobank/src/dao/VotingManagerDAO'>;
// }
// declare module '@chronobank/src/i18n/en-notices.js' {
//   declare export default $Exports<'@chronobank/src/i18n/en-notices'>;
// }
// declare module '@chronobank/src/i18n/en-tx-bitcoin.js' {
//   declare export default $Exports<'@chronobank/src/i18n/en-tx-bitcoin'>;
// }
// declare module '@chronobank/src/i18n/en-tx-general.js' {
//   declare export default $Exports<'@chronobank/src/i18n/en-tx-general'>;
// }
// declare module '@chronobank/src/i18n/en-tx-nem.js' {
//   declare export default $Exports<'@chronobank/src/i18n/en-tx-nem'>;
// }
// declare module '@chronobank/src/i18n/en.js' {
//   declare export default $Exports<'@chronobank/src/i18n/en'>;
// }
// declare module '@chronobank/src/i18n/index.js' {
//   declare export default $Exports<'@chronobank/src/i18n/index'>;
// }
// declare module '@chronobank/src/i18nApp.js' {
//   declare export default $Exports<'@chronobank/src/i18nApp'>;
// }
// declare module '@chronobank/src/index.js' {
//   declare export default $Exports<'@chronobank/src/index'>;
// }
// declare module '@chronobank/src/Login/network/VotingProvider.js' {
//   declare export default $Exports<'@chronobank/src/Login/network/VotingProvider'>;
// }
// declare module '@chronobank/src/market/__mocks__/socket.io-client.js' {
//   declare export default $Exports<'@chronobank/src/market/__mocks__/socket.io-client'>;
// }
// declare module '@chronobank/src/market/ccc-streamer-utilities.js' {
//   declare export default $Exports<'@chronobank/src/market/ccc-streamer-utilities'>;
// }
// declare module '@chronobank/src/market/MarketSocket.js' {
//   declare export default $Exports<'@chronobank/src/market/MarketSocket'>;
// }
// declare module '@chronobank/src/menu.js' {
//   declare export default $Exports<'@chronobank/src/menu'>;
// }
declare module '@chronobank/src/models/AbstractFetchingCollection.js' {
  declare export default $Exports<'AbstractFetchingCollection'>;
}
declare module '@chronobank/src/models/AbstractFetchingModel.js' {
  declare export default $Exports<'AbstractFetchingModel'>;
}
declare module '@chronobank/src/models/AbstractModel.js' {
  declare export default $Exports<'AbstractModel'>;
}
// declare module '@chronobank/src/models/AdditionalActionModel.js' {
//   declare export default $Exports<'@chronobank/src/models/AdditionalActionModel'>;
// }
declare module '@chronobank/src/models/Amount.js' {
  declare export default $Exports<'Amount'>;
}
// declare module '@chronobank/src/models/assetHolder/AssetHolderModel.js' {
//   declare export default $Exports<'@chronobank/src/models/assetHolder/AssetHolderModel'>;
// }
// declare module '@chronobank/src/models/assetHolder/AssetModel.js' {
//   declare export default $Exports<'@chronobank/src/models/assetHolder/AssetModel'>;
// }
// declare module '@chronobank/src/models/assetHolder/AssetsCollection.js' {
//   declare export default $Exports<'@chronobank/src/models/assetHolder/AssetsCollection'>;
// }
// declare module '@chronobank/src/models/assetsManager/MainAssetsManagerModel.js' {
//   declare export default $Exports<'@chronobank/src/models/assetsManager/MainAssetsManagerModel'>;
// }
// declare module '@chronobank/src/models/CBEModel.js' {
//   declare export default $Exports<'@chronobank/src/models/CBEModel'>;
// }
// declare module '@chronobank/src/models/constants.js' {
//   declare export default $Exports<'@chronobank/src/models/constants'>;
// }
// declare module '@chronobank/src/models/exchange/ExchangeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/exchange/ExchangeModel'>;
// }
// declare module '@chronobank/src/models/exchange/ExchangeOrderModel.js' {
//   declare export default $Exports<'@chronobank/src/models/exchange/ExchangeOrderModel'>;
// }
// declare module '@chronobank/src/models/exchange/ExchangesCollection.js' {
//   declare export default $Exports<'@chronobank/src/models/exchange/ExchangesCollection'>;
// }
// declare module '@chronobank/src/models/FileSelect/FileCollection.js' {
//   declare export default $Exports<'@chronobank/src/models/FileSelect/FileCollection'>;
// }
// declare module '@chronobank/src/models/FileSelect/FileExtension.js' {
//   declare export default $Exports<'@chronobank/src/models/FileSelect/FileExtension'>;
// }
// declare module '@chronobank/src/models/FileSelect/FileModel.js' {
//   declare export default $Exports<'@chronobank/src/models/FileSelect/FileModel'>;
// }
// declare module '@chronobank/src/models/LOCModel.js' {
//   declare export default $Exports<'@chronobank/src/models/LOCModel'>;
// }
// declare module '@chronobank/src/models/notices/AbstractNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/AbstractNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/ApprovalNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/ApprovalNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/ArbitraryNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/ArbitraryNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/AssetsManagerNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/AssetsManagerNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/CBENoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/CBENoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/ErrorNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/ErrorNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/LOCNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/LOCNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/OperationNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/OperationNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/PollNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/PollNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/ProfileNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/ProfileNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/TokenNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/TokenNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/TransactionErrorNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/TransactionErrorNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/TransferErrorNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/TransferErrorNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/TransferNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/TransferNoticeModel'>;
// }
// declare module '@chronobank/src/models/notices/WalletNoticeModel.js' {
//   declare export default $Exports<'@chronobank/src/models/notices/WalletNoticeModel'>;
// }
// declare module '@chronobank/src/models/OperationModel.js' {
//   declare export default $Exports<'@chronobank/src/models/OperationModel'>;
// }
// declare module '@chronobank/src/models/PollDetailsModel.js' {
//   declare export default $Exports<'@chronobank/src/models/PollDetailsModel'>;
// }
// declare module '@chronobank/src/models/PollModel.js' {
//   declare export default $Exports<'@chronobank/src/models/PollModel'>;
// }
// declare module '@chronobank/src/models/ProfileModel.js' {
//   declare export default $Exports<'@chronobank/src/models/ProfileModel'>;
// }
// declare module '@chronobank/src/models/rewards/AbstractPeriodModel.js' {
//   declare export default $Exports<'@chronobank/src/models/rewards/AbstractPeriodModel'>;
// }
// declare module '@chronobank/src/models/rewards/RewardsCollection.js' {
//   declare export default $Exports<'@chronobank/src/models/rewards/RewardsCollection'>;
// }
// declare module '@chronobank/src/models/rewards/RewardsCurrentPeriodModel.js' {
//   declare export default $Exports<'@chronobank/src/models/rewards/RewardsCurrentPeriodModel'>;
// }
// declare module '@chronobank/src/models/rewards/RewardsModel.js' {
//   declare export default $Exports<'@chronobank/src/models/rewards/RewardsModel'>;
// }
// declare module '@chronobank/src/models/rewards/RewardsPeriodModel.js' {
//   declare export default $Exports<'@chronobank/src/models/rewards/RewardsPeriodModel'>;
// }
declare module '@chronobank/src/models/tokens/BalanceModel.js' {
  declare export default $Exports<'BalanceModel'>;
}
declare module '@chronobank/src/models/tokens/BalancesCollection.js' {
  declare export default $Exports<'BalancesCollection'>;
}
declare module '@chronobank/src/models/tokens/BlacklistModel.js' {
  declare export default $Exports<'BlacklistModel'>;
}
declare module '@chronobank/src/models/tokens/FeeModel.js' {
  declare export default $Exports<'FeeModel'>;
}
// declare module '@chronobank/src/models/tokens/PausedModel.js' {
//   declare export default $Exports<'@chronobank/src/models/tokens/PausedModel'>;
// }
// declare module '@chronobank/src/models/tokens/ReissuableModel.js' {
//   declare export default $Exports<'@chronobank/src/models/tokens/ReissuableModel'>;
// }
declare module '@chronobank/src/models/tokens/TokenModel.js' {
  declare export default $Exports<'TokenModel'>;
}
declare module '@chronobank/src/models/tokens/TokensCollection.js' {
  declare export default $Exports<'TokensCollection'>;
}
// declare module '@chronobank/src/models/TransferError.js' {
//   declare export default $Exports<'@chronobank/src/models/TransferError'>;
// }
// declare module '@chronobank/src/models/TransferExecModel.js' {
//   declare export default $Exports<'@chronobank/src/models/TransferExecModel'>;
// }
// declare module '@chronobank/src/models/TxError.js' {
//   declare export default $Exports<'@chronobank/src/models/TxError'>;
// }
// declare module '@chronobank/src/models/TxExecModel.js' {
//   declare export default $Exports<'@chronobank/src/models/TxExecModel'>;
// }
declare module '@chronobank/src/models/TxModel.js' {
  declare export default $Exports<'TxModel'>;
}
// declare module '@chronobank/src/models/validator.js' {
//   declare export default $Exports<'@chronobank/src/models/validator'>;
// }
// declare module '@chronobank/src/models/voting/VotingCollection.js' {
//   declare export default $Exports<'@chronobank/src/models/voting/VotingCollection'>;
// }
// declare module '@chronobank/src/models/voting/VotingMainModel.js' {
//   declare export default $Exports<'@chronobank/src/models/voting/VotingMainModel'>;
// }
declare module '@chronobank/src/models/wallet/AddressesCollection.js' {
  declare export default $Exports<'AddressesCollection'>;
}
// declare module '@chronobank/src/models/wallet/AddressModel.js' {
//   declare export default $Exports<'@chronobank/src/models/wallet/AddressModel'>;
// }
declare module '@chronobank/src/models/wallet/AllowanceCollection.js' {
  declare export default $Exports<'AllowanceCollection'>;
}
declare module '@chronobank/src/models/wallet/AllowanceModel.js' {
  declare export default $Exports<'AllowanceModel'>;
}
declare module '@chronobank/src/models/wallet/MainWalletModel.js' {
  declare export default $Exports<'MainWalletModel'>;
}
// declare module '@chronobank/src/models/wallet/MultisigTransactionModel.js' {
//   declare export default $Exports<'@chronobank/src/models/wallet/MultisigTransactionModel'>;
// }
declare module 'models/wallet/MultisigWalletCollection.js' {
  declare export default $Exports<'MultisigWalletCollection'>;
}
declare module 'models/wallet/MultisigWalletModel.js' {
  declare export default $Exports<'MultisigWalletModel'>;
}

declare module '@chronobank/src/models/wallet/MultisigWalletPendingTxCollection.js' {
  declare export default $Exports<'MultisigWalletPendingTxCollection'>;
}
// declare module '@chronobank/src/models/wallet/MultisigWalletPendingTxModel.js' {
//   declare export default $Exports<'@chronobank/src/models/wallet/MultisigWalletPendingTxModel'>;
// }
declare module '@chronobank/src/models/wallet/OwnerCollection.js' {
  declare export default $Exports<'OwnerCollection'>;
}
declare module '@chronobank/src/models/wallet/OwnerModel.js' {
  declare export default $Exports<'OwnerModel'>;
}
declare module '@chronobank/src/models/wallet/TransactionsCollection.js' {
  declare export default $Exports<'TransactionsCollection'>;
}
// declare module '@chronobank/src/pages/lib/AssetsPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/AssetsPage'>;
// }
// declare module '@chronobank/src/pages/lib/DashboardPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/DashboardPage'>;
// }
// declare module '@chronobank/src/pages/lib/ExchangePage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/ExchangePage'>;
// }
// declare module '@chronobank/src/pages/lib/index.js' {
//   declare export default $Exports<'@chronobank/src/pages/lib/index'>;
// }
// declare module '@chronobank/src/pages/lib/LOCPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/LOCPage'>;
// }
// declare module '@chronobank/src/pages/lib/OperationsPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/OperationsPage'>;
// }
// declare module '@chronobank/src/pages/lib/RewardsPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/RewardsPage'>;
// }
// declare module '@chronobank/src/pages/lib/SettingsPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/SettingsPage'>;
// }
// declare module '@chronobank/src/pages/lib/VotingPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/VotingPage'>;
// }
// declare module '@chronobank/src/pages/lib/WalletPage.jsx' {
//   declare export default $Exports<'@chronobank/src/pages/lib/WalletPage'>;
// }
// declare module '@chronobank/src/pages/LoginPage/LoginPage.js' {
//   declare export default $Exports<'@chronobank/src/pages/LoginPage/LoginPage'>;
// }
// declare module '@chronobank/src/pages/NotFound/NotFound.js' {
//   declare export default $Exports<'@chronobank/src/pages/NotFound/NotFound'>;
// }
// declare module '@chronobank/src/pages/PageBase.js' {
//   declare export default $Exports<'@chronobank/src/pages/PageBase'>;
// }
// declare module '@chronobank/src/platform/ErrorList.js' {
//   declare export default $Exports<'@chronobank/src/platform/ErrorList'>;
// }
// declare module '@chronobank/src/platform/i18n/index.js' {
//   declare export default $Exports<'@chronobank/src/platform/i18n/index'>;
// }
// declare module '@chronobank/src/platform/icons/index.js' {
//   declare export default $Exports<'@chronobank/src/platform/icons/index'>;
// }
// declare module '@chronobank/src/platform/imageValidator.js' {
//   declare export default $Exports<'@chronobank/src/platform/imageValidator'>;
// }
// declare module '@chronobank/src/redux/assetsHolder/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsHolder/actions'>;
// }
// declare module '@chronobank/src/redux/assetsHolder/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsHolder/index'>;
// }
// declare module '@chronobank/src/redux/assetsHolder/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsHolder/reducer'>;
// }
// declare module '@chronobank/src/redux/assetsManager/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsManager/actions'>;
// }
// declare module '@chronobank/src/redux/assetsManager/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsManager/index'>;
// }
// declare module '@chronobank/src/redux/assetsManager/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsManager/reducer'>;
// }
// declare module '@chronobank/src/redux/assetsManager/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/assetsManager/selectors'>;
// }
// declare module '@chronobank/src/redux/bootstrap/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/bootstrap/actions'>;
// }
// declare module '@chronobank/src/redux/configureStore.js' {
//   declare export default $Exports<'@chronobank/src/redux/configureStore'>;
// }
// declare module '@chronobank/src/redux/drawer/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/drawer/actions'>;
// }
// declare module '@chronobank/src/redux/drawer/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/drawer/index'>;
// }
// declare module '@chronobank/src/redux/drawer/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/drawer/reducer'>;
// }
// declare module '@chronobank/src/redux/ducks.js' {
//   declare export default $Exports<'@chronobank/src/redux/ducks'>;
// }
// declare module '@chronobank/src/redux/exchange/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/exchange/actions'>;
// }
// declare module '@chronobank/src/redux/exchange/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/exchange/index'>;
// }
// declare module '@chronobank/src/redux/exchange/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/exchange/reducer'>;
// }
// declare module '@chronobank/src/redux/i18n/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/i18n/actions'>;
// }
// declare module '@chronobank/src/redux/i18n/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/i18n/index'>;
// }
// declare module '@chronobank/src/redux/i18n/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/i18n/reducer'>;
// }
// declare module '@chronobank/src/redux/locs/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/locs/actions'>;
// }
// declare module '@chronobank/src/redux/locs/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/locs/index'>;
// }
// declare module '@chronobank/src/redux/locs/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/locs/reducer'>;
// }
// declare module '@chronobank/src/redux/locs/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/locs/selectors'>;
// }
// declare module '@chronobank/src/redux/mainWallet/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/mainWallet/actions'>;
// }
// declare module '@chronobank/src/redux/mainWallet/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/mainWallet/index'>;
// }
// declare module '@chronobank/src/redux/mainWallet/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/mainWallet/reducer'>;
// }
// declare module '@chronobank/src/redux/mainWallet/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/mainWallet/selectors'>;
// }
// declare module '@chronobank/src/redux/market/action.js' {
//   declare export default $Exports<'@chronobank/src/redux/market/action'>;
// }
// declare module '@chronobank/src/redux/market/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/market/index'>;
// }
// declare module '@chronobank/src/redux/market/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/market/reducer'>;
// }
// declare module '@chronobank/src/redux/modals/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/modals/actions'>;
// }
// declare module '@chronobank/src/redux/modals/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/modals/index'>;
// }
// declare module '@chronobank/src/redux/modals/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/modals/reducer'>;
// }
// declare module '@chronobank/src/redux/multisigWallet/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/multisigWallet/actions'>;
// }
// declare module '@chronobank/src/redux/multisigWallet/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/multisigWallet/index'>;
// }
// declare module '@chronobank/src/redux/multisigWallet/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/multisigWallet/reducer'>;
// }
// declare module '@chronobank/src/redux/notifier/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/notifier/actions'>;
// }
// declare module '@chronobank/src/redux/notifier/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/notifier/index'>;
// }
// declare module '@chronobank/src/redux/notifier/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/notifier/reducer'>;
// }
// declare module '@chronobank/src/redux/operations/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/operations/actions'>;
// }
// declare module '@chronobank/src/redux/operations/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/operations/index'>;
// }
// declare module '@chronobank/src/redux/operations/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/operations/reducer'>;
// }
// declare module '@chronobank/src/redux/rewards/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/rewards/actions'>;
// }
// declare module '@chronobank/src/redux/rewards/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/rewards/index'>;
// }
// declare module '@chronobank/src/redux/rewards/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/rewards/reducer'>;
// }
// declare module '@chronobank/src/redux/routing.js' {
//   declare export default $Exports<'@chronobank/src/redux/routing'>;
// }
// declare module '@chronobank/src/redux/session/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/session/actions'>;
// }
// declare module '@chronobank/src/redux/session/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/session/index'>;
// }
// declare module '@chronobank/src/redux/session/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/session/reducer'>;
// }
// declare module '@chronobank/src/redux/session/saveAccountMiddleWare.js' {
//   declare export default $Exports<'@chronobank/src/redux/session/saveAccountMiddleWare'>;
// }
// declare module '@chronobank/src/redux/session/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/session/selectors'>;
// }
// declare module '@chronobank/src/redux/settings/erc20/tokens/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/erc20/tokens/actions'>;
// }
// declare module '@chronobank/src/redux/settings/erc20/tokens/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/erc20/tokens/reducer'>;
// }
// declare module '@chronobank/src/redux/settings/erc20/tokens/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/erc20/tokens/selectors'>;
// }
// declare module '@chronobank/src/redux/settings/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/index'>;
// }
// declare module '@chronobank/src/redux/settings/user/cbe/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/user/cbe/actions'>;
// }
// declare module '@chronobank/src/redux/settings/user/cbe/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/settings/user/cbe/reducer'>;
// }
// declare module '@chronobank/src/redux/sides/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/sides/actions'>;
// }
// declare module '@chronobank/src/redux/sides/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/sides/index'>;
// }
// declare module '@chronobank/src/redux/sides/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/sides/reducer'>;
// }
// declare module '@chronobank/src/redux/tokens/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/tokens/actions'>;
// }
// declare module '@chronobank/src/redux/tokens/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/tokens/index'>;
// }
// declare module '@chronobank/src/redux/tokens/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/tokens/reducer'>;
// }
// declare module '@chronobank/src/redux/tokens/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/tokens/selectors'>;
// }
// declare module '@chronobank/src/redux/ui/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/ui/actions'>;
// }
// declare module '@chronobank/src/redux/ui/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/ui/index'>;
// }
// declare module '@chronobank/src/redux/ui/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/ui/reducer'>;
// }
// declare module '@chronobank/src/redux/voting/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/voting/actions'>;
// }
// declare module '@chronobank/src/redux/voting/getters.js' {
//   declare export default $Exports<'@chronobank/src/redux/voting/getters'>;
// }
// declare module '@chronobank/src/redux/voting/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/voting/index'>;
// }
// declare module '@chronobank/src/redux/voting/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/voting/reducer'>;
// }
// declare module '@chronobank/src/redux/wallet/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/wallet/actions'>;
// }
// declare module '@chronobank/src/redux/wallet/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/wallet/index'>;
// }
// declare module '@chronobank/src/redux/wallet/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/wallet/reducer'>;
// }
// declare module '@chronobank/src/redux/wallet/selectors.js' {
//   declare export default $Exports<'@chronobank/src/redux/wallet/selectors'>;
// }
// declare module '@chronobank/src/redux/watcher/actions.js' {
//   declare export default $Exports<'@chronobank/src/redux/watcher/actions'>;
// }
// declare module '@chronobank/src/redux/watcher/index.js' {
//   declare export default $Exports<'@chronobank/src/redux/watcher/index'>;
// }
// declare module '@chronobank/src/redux/watcher/reducer.js' {
//   declare export default $Exports<'@chronobank/src/redux/watcher/reducer'>;
// }
// declare module '@chronobank/src/router.js' {
//   declare export default $Exports<'@chronobank/src/router'>;
// }
// declare module '@chronobank/src/services/ExchangeService.js' {
//   declare export default $Exports<'@chronobank/src/services/ExchangeService'>;
// }
// declare module '@chronobank/src/services/MultisigWalletService.js' {
//   declare export default $Exports<'@chronobank/src/services/MultisigWalletService'>;
// }
// declare module '@chronobank/src/services/TokenService.js' {
//   declare export default $Exports<'@chronobank/src/services/TokenService'>;
// }
// declare module '@chronobank/src/services/VotingService.js' {
//   declare export default $Exports<'@chronobank/src/services/VotingService'>;
// }
// declare module '@chronobank/src/specsInit.js' {
//   declare export default $Exports<'@chronobank/src/specsInit'>;
// }
// declare module '@chronobank/src/styles.js' {
//   declare export default $Exports<'@chronobank/src/styles'>;
// }
// declare module '@chronobank/src/styles/themes/default.js' {
//   declare export default $Exports<'@chronobank/src/styles/themes/default'>;
// }
// declare module '@chronobank/src/styles/themes/inversed.js' {
//   declare export default $Exports<'@chronobank/src/styles/themes/inversed'>;
// }
// declare module '@chronobank/src/styles/themes/variables.js' {
//   declare export default $Exports<'@chronobank/src/styles/themes/variables'>;
// }
// declare module '@chronobank/src/themeDefault.js' {
//   declare export default $Exports<'@chronobank/src/themeDefault'>;
// }
// declare module '@chronobank/src/user/monitorService.js' {
//   declare export default $Exports<'@chronobank/src/user/monitorService'>;
// }
// declare module '@chronobank/src/utils/clipboard.js' {
//   declare export default $Exports<'@chronobank/src/utils/clipboard'>;
// }
// declare module '@chronobank/src/utils/CustomSerializer.js' {
//   declare export default $Exports<'@chronobank/src/utils/CustomSerializer'>;
// }
// declare module '@chronobank/src/utils/formatFileSize.js' {
//   declare export default $Exports<'@chronobank/src/utils/formatFileSize'>;
// }
// declare module '@chronobank/src/utils/formatter.js' {
//   declare export default $Exports<'@chronobank/src/utils/formatter'>;
// }
// declare module '@chronobank/src/utils/IPFS.js' {
//   declare export default $Exports<'@chronobank/src/utils/IPFS'>;
// }
// declare module '@chronobank/src/utils/LocalStorage.js' {
//   declare export default $Exports<'@chronobank/src/utils/LocalStorage'>;
// }
// declare module '@chronobank/src/utils/SessionStorage.js' {
//   declare export default $Exports<'@chronobank/src/utils/SessionStorage'>;
// }
// declare module '@chronobank/src/utils/Web3Converter.js' {
//   declare export default $Exports<'@chronobank/src/utils/Web3Converter'>;
// }
