export const DUCK_WEB3_MIDDLEWARE = 'web3_middleware'

export const WEB3_MIDDLEWARE_INIT = 'WEB3_MIDDLEWARE/INIT'

export const WEB3_MIDDLEWARE_CONNECT = 'WEB3_MIDDLEWARE/CONNECT'
export const WEB3_MIDDLEWARE_CONNECT_FAILURE = 'WEB3_MIDDLEWARE/CONNECT_FAILURE'
export const WEB3_MIDDLEWARE_CONNECT_SUCCESS = 'WEB3_MIDDLEWARE/CONNECT_SUCCESS'
export const WEB3_MIDDLEWARE_DISCONNECT = 'WEB3_MIDDLEWARE/DISCONNECT'

export const WEB3_MIDDLEWARE_SUBSCRIBE = 'WEB3_MIDDLEWARE/SUBSCRIBE'
export const WEB3_MIDDLEWARE_SUBSCRIBE_FAILURE = 'WEB3_MIDDLEWARE/SUBSCRIBE_FAILURE'
export const WEB3_MIDDLEWARE_SUBSCRIBE_SUCCESS = 'WEB3_MIDDLEWARE/SUBSCRIBE_SUCCESS'
export const WEB3_MIDDLEWARE_UNSUBSCRIBE = 'WEB3_MIDDLEWARE/UNSUBSCRIBE'

export const WEB3_MIDDLEWARE_APPEND_CONTRACT = 'WEB3_MIDDLEWARE/APPEND_CONTRACT'
export const WEB3_MIDDLEWARE_INCOMPATIBLE_NETWORK = 'WEB3_MIDDLEWARE/INCOMPATIBLE_NETWORK'
export const WEB3_MIDDLEWARE_RESET = 'WEB3_MIDDLEWARE/RESET'

export const WEB3_MIDDLEWARE_METHOD_ESTIMATE_GAS = 'WEB3_MIDDLEWARE/METHOD_ESTIMATE_GAS'
export const WEB3_MIDDLEWARE_METHOD_GET_BALANCE = 'WEB3_MIDDLEWARE/METHOD_GET_BALANCE'
export const WEB3_MIDDLEWARE_METHOD_GET_CHAIN_ID = 'WEB3_MIDDLEWARE/METHOD_GET_CHAIN_ID'
export const WEB3_MIDDLEWARE_METHOD_GET_GAS_PRICE = 'WEB3_MIDDLEWARE/METHOD_GET_GAS_PRICE'
export const WEB3_MIDDLEWARE_METHOD_GET_NONCE = 'WEB3_MIDDLEWARE/METHOD_GET_NONCE'
export const WEB3_MIDDLEWARE_METHOD_GET_NONCE_HEX = 'WEB3_MIDDLEWARE/METHOD_GET_NONCE_HEX'
export const WEB3_MIDDLEWARE_METHOD_SEND_SIGNED_TX = 'WEB3_MIDDLEWARE/METHOD_SEND_SIGNED_TX'
