/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_ETHEREUM = 'ethereum'

export const ETHEREUM_CREATE_DERIVED_WALLET = 'ETHEREUM/CREATE_DERIVED_WALLET'
export const ETHEREUM_CREATE_TX_DRAFT = 'ETHEREUM/CREATE_TX_DRAFT'
export const ETHEREUM_DELETE_TX_DRAFT = 'ETHEREUM/DELETE_TX_DRAFT'
export const ETHEREUM_CREATE_WALLET = 'ETHERIUM/CREATE_WALLET'
export const ETHEREUM_SELECT_WALLET = 'ETHEREUM/SELECT_WALLET'
export const ETHEREUM_DROP_SELECTED_WALLET = 'ETHEREUM/DROP_SELECTED_WALLET'
export const ETHEREUM_UPDATE_BALANCE = 'ETHEREUM/UPDATE_BALANCE'

export const ETHEREUM_TX_UPDATE_HISTORY = 'ETHEREUM/TX_UPDATE_HISTORY'
export const ETHEREUM_UPDATE_TX_DRAFT_CHAIN_ID = 'ETHEREUM/UPDATE_TX_DRAFT/CHAIN_ID'
export const ETHEREUM_UPDATE_TX_DRAFT_DATA = 'ETHEREUM/UPDATE_TX_DRAFT/DATA'
export const ETHEREUM_UPDATE_TX_DRAFT_GAS_LIMIT = 'ETHEREUM/UPDATE_TX_DRAFT/GAS_LIMIT'
export const ETHEREUM_UPDATE_TX_DRAFT_GAS_PRICE = 'ETHEREUM/UPDATE_TX_DRAFT/GAS_PRICE'
export const ETHEREUM_UPDATE_TX_DRAFT_NONCE = 'ETHEREUM/UPDATE_TX_DRAFT/NONCE'
export const ETHEREUM_UPDATE_TX_DRAFT_SIGNED_TX = 'ETHEREUM/UPDATE_TX_DRAFT/SIGNED_TX'
export const ETHEREUM_UPDATE_TX_DRAFT_TO = 'ETHEREUM/UPDATE_TX_DRAFT/TO'
export const ETHEREUM_UPDATE_TX_DRAFT_VALUE = 'ETHEREUM/UPDATE_TX_DRAFT/VALUE'
